<<<<<<< HEAD
# Generated by Django 5.2.9 on 2025-12-21 13:14
=======
# Generated by Django 5.2.9 on 2026-01-01 11:27
>>>>>>> 7f5859f (update)

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('auth', '0012_alter_user_first_name_max_length'),
=======
>>>>>>> 7f5859f (update)
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
<<<<<<< HEAD
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
=======
>>>>>>> 7f5859f (update)
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone_number', models.CharField(max_length=50)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
<<<<<<< HEAD
                ('last_login', models.DateTimeField(auto_now_add=True)),
=======
                ('last_login', models.DateTimeField(auto_now=True)),
>>>>>>> 7f5859f (update)
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_superadmin', models.BooleanField(default=False)),
<<<<<<< HEAD
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
=======
            ],
            options={
>>>>>>> 7f5859f (update)
                'abstract': False,
            },
        ),
    ]
