<<<<<<< HEAD
# Generated by Django 5.2.9 on 2025-12-21 13:14
=======
# Generated by Django 5.2.9 on 2026-01-01 11:27
>>>>>>> 7f5859f (update)

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cat_image', models.ImageField(blank=True, null=True, upload_to='photos/categories/')),
=======
                ('category_name', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cat_image', models.ImageField(blank=True, null=True, upload_to='photos/categories')),
>>>>>>> 7f5859f (update)
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
<<<<<<< HEAD
=======
                'ordering': ['category_name'],
>>>>>>> 7f5859f (update)
            },
        ),
    ]
